name: Tweet Liker

on:
  push:
  schedule:
    - cron: "*/22 * * * *"

jobs:
  liking-tweets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install dependancies
        run: pip install tweepy python-dotenv
      - name: retweeting babyyyyy
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
        run: python searchbot.py
